---
- name: Create Application Load Balancer
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars_file.yaml
  ignore_errors: yes
  tasks:

  - elb_application_lb:
      name: "{{name}}
      security_group: "{{security_groups}}"
      region: "{{region}}"
      subnets:
        - "{{pub_subnet1}}"
        - "{{pub_subnet2}}"
        - "{{pub_subnet3}}"
      listeners:
        - Protocol: "{{ HTTP }}" # Required. The protocol for connections from clients to the load balancer (HTTP or HTTPS) (case-sensitive).
          Port: "{{ 80 }}"
          DefaultActions:
            - Type: "{{ forward }}" # Required.
              TargetGroupName: "{{ mytargetgroup }}"
      state: present
