---
- name: Create Launch Config
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yaml

  tasks:
  - name: Create Launch Config
    ec2_lc:
      name: team2-lc
      image_id: "{{image_id}}"
      key_name: "{{key_name}}"
      security_groups: "{{security_groups}}"
      instance_type: "{{instance_type}}"
      region: "{{region}}"
      volumes:
      - device_name: /dev/xvda
        volume_size: 100
        volume_type: io1
        iops: 3000
        delete_on_termination: true
        encrypted: no
    register: lc
