---
- name: Create Target Group
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars_file.yaml
  ignore_errors: yes
  tasks:

  - elb_target_group:
      name: "{{name}}"
      region: "{{region}}"
      protocol: http
      port: 80
      vpc_id: "{{vpc_id}}"
      state: present
