---
- name: Create Auto Scaling Group
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars_file.yaml
  ignore_errors: yes
  task:

  - ec2_asg:
      name: "{{name}}"
      launch_config_name: {{launch_config_name}}"
      vpc_zone_identifier:
        - "{{pub_subnet1}}"
        - "{{pub_subnet2}}"
        - "{{pub_subnet3}}"
      health_check_period: "{{health_check_period}}"
      health_check_type: ELB
      replace_all_instances: yes
      min_size: "{{min_size}}"
      max_size: "{{max_size}}"
      desired_capacity: "{{desired_capacity}}"
      region: "{{region}}"
      state: present
